server:
  port: 8301

spring:
#  application:
#    name: borrow-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/library?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    username: root
#    password: root
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        # 将ephemeral修改为false，表示非临时实例
        ephemeral: false
        # 修改为南京地区的集群
        cluster-name: NanJing
    loadbalancer:
      nacos:
        enabled: true