server:
  port: 8101

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        # 修改为南京地区的集群
        cluster-name: NanJing
#        # 命名空间
#        namespace: 5f3efcde-3a25-41c3-8830-c250575be78d
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
      # 关闭Context收敛，这样被监控方法可以进行不同链路的单独控制
      web-context-unify: false
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
seata:
  service:
    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
      # 这个很关键，一定要配置对，不然会找不到服务
      user-service-seata-service-group: default
    grouplist:
      default: localhost:8868